export {default as Home} from "./home/Home"
export {default as Login} from "./login/Login"
export {default as Register} from "./register/Register"
export {default as RegisterTwo} from "./register-two/RegisterTwo"
export {default as RegisterThree} from "./register-three/RegisterThree"
export {default as Profile} from "./profile/Profile"
